In [1]:
from keras.datasets import mnist

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [4]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [5]:
import cv2

In [6]:
cv2.imshow('window',X_train[0])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
y_train[0]

5

In [8]:
60000, 28, 28, 1

(60000, 28, 28, 1)

In [9]:
X_train = X_train.reshape(60000, 28, 28, 1)
X_test = X_test.reshape(10000, 28, 28, 1)

In [10]:
X_train.shape

(60000, 28, 28, 1)

In [11]:
X_train.shape, X_test.shape

((60000, 28, 28, 1), (10000, 28, 28, 1))

In [12]:
X_train

array([[[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]]],


       [[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],


In [13]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [14]:
X_train

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [15]:
X_train.shape

(60000, 28, 28, 1)

In [16]:
X_train = X_train / 255
X_test = X_test / 255

In [17]:
X_train[0]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [18]:
from keras.utils import np_utils

In [19]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)

In [20]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [21]:
y_train.shape

(60000, 10)

In [22]:
y_test.shape

(10000, 10)

In [23]:
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout

In [24]:
from keras.optimizers import SGD, RMSprop
from keras import backend as k

In [25]:
model = Sequential()

In [26]:
model.add(Conv2D(32, kernel_size= (3,3), activation='relu', input_shape=(28, 28, 1)))
model.add(Conv2D(64, kernel_size= (3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(250, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer = SGD(0.01), metrics=['accuracy'])

In [27]:
model.fit(X_train, y_train, batch_size = 1000, epochs = 2, verbose=1, validation_data = (X_test, y_test))
model.evaluate(X_test, y_test)

Epoch 1/2
60/60 [==============================] - 118s 2s/step - loss: 2.2401 - accuracy: 0.2855 - val_loss: 2.1105 - val_accuracy: 0.5395
Epoch 2/2
313/313 [==============================] - 9s 29ms/step - loss: 0.9208 - accuracy: 0.8115


[0.9207704067230225, 0.8115000128746033]

In [28]:
X_test.shape

(10000, 28, 28, 1)

In [29]:
res = model.predict(X_test)
index=[]

In [34]:
res


In [36]:
import numpy as np

In [38]:
for i in range(len(res)):
    index.append(np.argmax(res[i]))
    

In [39]:
index

[7,
 2,
 1,
 0,
 4,
 1,
 4,
 9,
 5,
 7,
 0,
 6,
 9,
 0,
 1,
 3,
 9,
 7,
 3,
 4,
 9,
 6,
 4,
 5,
 4,
 0,
 7,
 4,
 0,
 1,
 3,
 1,
 3,
 0,
 7,
 2,
 7,
 1,
 3,
 1,
 1,
 7,
 4,
 2,
 3,
 3,
 3,
 2,
 4,
 4,
 6,
 3,
 5,
 3,
 2,
 0,
 4,
 1,
 4,
 5,
 7,
 8,
 9,
 2,
 7,
 9,
 2,
 4,
 3,
 0,
 7,
 0,
 2,
 8,
 1,
 7,
 3,
 7,
 1,
 7,
 9,
 6,
 2,
 7,
 8,
 4,
 7,
 3,
 6,
 1,
 3,
 6,
 8,
 3,
 1,
 4,
 9,
 7,
 6,
 9,
 6,
 0,
 5,
 4,
 9,
 9,
 2,
 1,
 9,
 4,
 8,
 1,
 3,
 9,
 9,
 9,
 4,
 4,
 9,
 7,
 3,
 6,
 7,
 6,
 7,
 9,
 0,
 5,
 8,
 5,
 6,
 6,
 3,
 7,
 8,
 1,
 0,
 1,
 6,
 4,
 6,
 7,
 3,
 1,
 9,
 1,
 8,
 2,
 0,
 4,
 9,
 9,
 5,
 3,
 1,
 5,
 6,
 0,
 3,
 9,
 4,
 6,
 5,
 4,
 6,
 3,
 4,
 4,
 1,
 4,
 4,
 7,
 3,
 3,
 2,
 1,
 1,
 8,
 1,
 8,
 1,
 8,
 8,
 0,
 3,
 9,
 2,
 3,
 0,
 1,
 1,
 3,
 0,
 9,
 0,
 3,
 1,
 6,
 4,
 2,
 3,
 6,
 1,
 1,
 1,
 3,
 9,
 3,
 2,
 9,
 4,
 8,
 9,
 3,
 9,
 0,
 3,
 5,
 7,
 3,
 7,
 2,
 2,
 7,
 1,
 2,
 7,
 4,
 1,
 7,
 3,
 3,
 8,
 7,
 7,
 9,
 2,
 2,
 4,
 1,
 3,
 3,
 8,
 4,
 2,
 6,
 0,
 6,
 4,
 2,


In [40]:
print()

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [45]:
index=[]
import cv2
for i in range(10):
    index.append(np.argmax(res[i]))
    print(index[i])
    cv2.imshow("Window",X_test[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()


7
2
1
0
4
1
4
9
5
7


In [ ]:
cv2.imshow("Window",X_test[200])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
val = list(res[200])

In [ ]:
for i in val:
    print("{:.7f}". format(i))